
import { CheckCircle, Hammer, Home, Layers, MapPin, Star, Wrench } from 'lucide-react';
import ContactForm from './ContactForm';
const PHONE_RAW = '+12074513163'; const ADDRESS='3 Smalls Way, York, ME 03909'; const PHONE = '+1 (207) 451-3163';

export function Services() {
  const items = [
    { title: 'Roof Replacement', desc: 'Tear‑offs & re‑roofs using premium shingles installed to spec.', icon: Home, bullets: ['CertainTeed Landmark / Grand Manor','Starter, underlayment, ridge vent','Warranty‑backed installs'] },
    { title: 'Roof Repair & Leaks', desc: 'Emergency patches, pipe boots, flashing, storm damage.', icon: Wrench, bullets: ['Ice dams & wind lift','Chimney & valley flashing','Skylight leaks'] },
    { title: 'Metal & Flat Roofing', desc: 'Standing‑seam metal and EPDM/modified bitumen for select projects.', icon: Layers, bullets: ['Metal accents & porches','Low‑slope solutions','Snow‑belt detailing'] }
  ];
  return (<section id="services" className="py-16 md:py-24"><div className="container"><div className="mx-auto max-w-2xl text-center"><h2 className="text-3xl font-bold tracking-tight md:text-4xl text-navy">Roofing services built for New Engalnd weather</h2><p className="mt-3 text-neutral-700">Proper underlayment, ventilation and materials—installed by a crew that treats your home like their own.</p></div><div className="mt-10 grid grid-cols-1 gap-6 md:grid-cols-3">{items.map((s)=>(<div key={s.title} className="group relative card p-6 transition hover:shadow-lg"><s.icon className="h-6 w-6 text-ocean"/><h3 className="mt-4 text-xl font-semibold">{s.title}</h3><p className="mt-2 text-sm text-neutral-600">{s.desc}</p><ul className="mt-4 space-y-2 text-sm text-neutral-700">{s.bullets.map(b=>(<li key={b} className="flex items-start gap-2"><CheckCircle className="mt-0.5 h-4 w-4 flex-none text-teal"/>{b}</li>))}</ul></div>))}</div></div></section>);
}

export function PromoCTA(){return(<section className="relative isolate overflow-hidden bg-navy py-12 text-white md:py-16"><div className="container items-center justify-between gap-8 md:flex"><div><h3 className="text-2xl font-bold tracking-tight">Need a roof estimate fast?</h3><p className="mt-2 text-white/85">Text photos of the front & back of your home and we’ll provide a ballpark same‑day.</p></div><div className="mt-6 flex gap-3 md:mt-0"><a href={`tel:${PHONE_RAW}`} className="rounded-xl bg-teal px-5 py-3 font-semibold text-navy shadow hover:bg-teal/90">Call Now</a><a href="/#contact" className="rounded-xl border border-white/20 px-5 py-3 font-semibold hover:bg-white/10">Email Photos</a></div></div></section>);}

export function Reviews(){const items=[{name:'Hanna F.',quote:'These guys are terrific—polite, professional, and they get the job done right. My new roof looks amazing!'},{name:'Rene M.',quote:'On time. Great work. Would recommend!'}];return(<section id="reviews" className="py-16 md:py-24"><div className="container"><div className="mx-auto max-w-2xl text-center"><h2 className="text-3xl font-bold tracking-tight md:text-4xl text-navy">What neighbors are saying</h2><p className="mt-3 text-neutral-700">Real, local feedback about working with our crew.</p></div><div className="mt-10 grid grid-cols-1 gap-6 md:grid-cols-2">{items.map(r=>(<blockquote key={r.name} className="rounded-xl border border-neutral-200 bg-white p-6 shadow-soft"><svg xmlns='http://www.w3.org/2000/svg' className='h-5 w-5 text-ocean' viewBox='0 0 24 24' fill='currentColor'><path d='M12 .587l3.668 7.431 8.2 1.192-5.934 5.787 1.402 8.168L12 18.896l-7.336 3.869 1.402-8.168L.132 9.21l8.2-1.192z'/></svg><p className='mt-3 text-neutral-800'>“{r.quote}”</p><footer className='mt-3 text-sm text-neutral-600'>— {r.name}</footer></blockquote>))}</div></div></section>);}

export function ServiceArea(){const areas=['York','Kittery','Kittery Point','Ogunquit','Eliot','South Berwick','Wells','Portsmouth NH'];return(<section id="service-area" className="bg-navy ... py-16 text-white md:py-24"><div className="container items-center gap-10 md:flex"><div className="md:w-1/2"><h2 className="text-3xl font-bold tracking-tight md:text-4xl">Proudly serving the Seacoast</h2><p className="mt-3 text-white/85">We’re based in York and work across Southern Maine and the NH Seacoast.</p><ul className="mt-4 grid grid-cols-2 gap-2 text-sm text-white/90 md:grid-cols-3">{areas.map(a=>(<li key={a} className="flex items-center gap-2"><span className="inline-block h-2 w-2 rounded-full bg-teal"/>{a}</li>))}</ul></div><div className="mt-8 md:mt-0 md:w-1/2"><div className="rounded-xl border border-white/15 bg-white/5 p-6"><div className="text-sm text-white/75">Shop:</div><div className="mt-1 font-medium">3 Smalls Way, York, ME 03909</div><div className="mt-3 text-sm text-white/75">Phone:</div><a href={`tel:${PHONE_RAW}`} className="mt-1 inline-block font-medium text-white underline underline-offset-4">{PHONE}</a></div></div></div></section>);}

export function Contact(){return(<section id="contact" className="py-16 md:py-24"><div className="container"><div className="mx-auto max-w-2xl text-center"><h2 className="text-3xl font-bold tracking-tight md:text-4xl text-navy">Get your free, no‑pressure estimate</h2><p className="mt-3 text-neutral-700">Call or email and we’ll schedule a quick on‑site visit.</p></div><div className="mx-auto mt-8 max-w-xl rounded-xl border border-neutral-200 bg-white p-6 shadow-soft"><ContactForm/><div className="mt-4 text-center text-sm text-neutral-600">Prefer phone? <a href={`tel:${PHONE_RAW}`} className="font-medium text-ocean underline underline-offset-4">Call (207) 451-3163</a></div></div></div></section>);}

export function JsonLd(){const json={"@context":"https://schema.org","@type":"RoofingContractor",name:'Sky High Roofing & General Contracting',address:{"@type":"PostalAddress",streetAddress:"3 Smalls Way",addressLocality:"York",addressRegion:"ME",postalCode:"03909",addressCountry:"US"},telephone:"+1 (207) 451-3163",areaServed:['York','Kittery','Ogunquit','Eliot','South Berwick','Wells','Portsmouth NH'],url:process.env.NEXT_PUBLIC_SITE_URL||"http://localhost:3030",sameAs:["https://www.facebook.com/skyhighgeneralcontracting"]};return(<script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(json) }} />);}
